Repository Activiti/activiti-cloud-connectors, pull requests merged in 2018-11, with the labels that each got.

#58 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.41
  pom.xml
Labels: updatebot

#60 Configure Updatebot single PR for cloud-dependencies tests and automatic merge with Mergify
  .mergify.yml
  .updatebot.yml
Labels: enhancement, in progress

#59 update org.activiti.cloud.build:activiti-cloud-parent to 7.0.36
  pom.xml
Labels: in progress, updatebot

#61 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.47
  pom.xml
Labels: in progress, updatebot

#62 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#63 Add activiti-cloud-connectors-dependencies-tests module
  .mergify.yml
  activiti-cloud-connectors-dependencies/pom.xml
  activiti-cloud-starter-connector/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#64 fix(versions): update Activiti/activiti-cloud-connectors versions
  pom.xml
Labels: in progress, updatebot

#65 fix(versions): update Activiti/activiti-cloud-connectors versions
  pom.xml
Labels: in progress, updatebot

#66 fix(versions): update Activiti/activiti-cloud-connectors versions
  pom.xml
Labels: in progress, updatebot

#67 fix(versions): update Activiti/activiti-cloud-connectors versions
  pom.xml
Labels: updatebot

#68 fix(versions): update Activiti/activiti-cloud-connectors versions
  pom.xml
Labels: in progress, updatebot

#69 fix(versions): update Activiti/activiti-cloud-connectors versions
  pom.xml
Labels: in progress, updatebot
